global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    basic_auth:
      username: "admin"
      password: "4c95637bc9033f6b3c402034b2e0705f"
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          instance: prometheus

  - job_name: gost
    static_configs:
      - targets: [ 'gost:19000' ]
        labels:
          instance: gost