global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          instance: prometheus

  - job_name: gost
    scrape_interval: 5s
    static_configs:
      - targets: [ '172.17.0.1:19000' ]
        labels:
          instance: gost