name: Build docker image nightly

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Delete untagged images
      run: |
        REPO=${{ github.event.repository.name }}
        TOKEN=${{ secrets.GITHUB_TOKEN }}
        TAGS=$(curl -s -H "Authorization: Bearer $TOKEN" \
               "https://api.github.com/user/packages/container/$REPO/versions?per_page=100" \
               | jq -r '.[] | select(.metadata.container.tags | length==0) | .id')
        for TAG in $TAGS; do
          curl -s -X DELETE -H "Authorization: Bearer $TOKEN" \
               "https://api.github.com/user/packages/container/$REPO/versions/$TAG"
        done